# Generated by Django 4.2 on 2023-04-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_url', models.CharField(max_length=250)),
                ('emp_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_str', models.CharField(max_length=100)),
                ('search_date', models.CharField(max_length=25)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=250)),
                ('vacancy_url', models.CharField(max_length=250)),
                ('salary_grace', models.CharField(max_length=5)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.employer')),
                ('salary_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.currency')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.schedule')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.search_vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='search_vacancy',
            name='skill_id',
            field=models.ManyToManyField(to='hh_search_app.skill'),
        ),
        migrations.CreateModel(
            name='Search_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_search_app.search_vacancy')),
            ],
        ),
    ]
