# Generated by Django 4.2 on 2023-04-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0002_alter_search_vacancy_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search_vacancy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(default=-1000),
        ),
        migrations.AddField(
            model_name='search_salary',
            name='count_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search_salary',
            name='high_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='search_salary',
            name='low_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='search_vacancy',
            name='count_vacancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search_vacancy',
            name='strict_search',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='search_vacancy',
            unique_together={('search_str', 'region_id', 'strict_search')},
        ),
    ]
