# Generated by Django 4.2 on 2023-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0003_alter_search_vacancy_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='None', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
