# Generated by Django 4.2 on 2023-04-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0004_remove_currency_exchange_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
