# Generated by Django 4.2 on 2023-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0006_alter_vacancy_vacancy_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_grace',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
