# Generated by Django 4.2 on 2023-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0007_alter_vacancy_salary_grace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='emp_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
