# Generated by Django 4.2 on 2023-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search_app', '0008_alter_employer_emp_id_alter_employer_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='emp_id',
            field=models.CharField(max_length=25),
        ),
    ]
